'use strict';
const $=id=>document.getElementById(id);
let chapters=[],selected=null,last=null;
function choose(c){selected=c; $('chapterNumber').textContent=`CHAPTER ${String(c.chapter).padStart(2,'0')}`;$('title').textContent=c.lab_title;$('subtitle').textContent=c.title;$('engine').textContent=c.engine.toUpperCase();$('hypothesis').textContent=c.hypothesis;$('exercise').textContent=c.exercise;$('boundary').textContent='Interpretation boundary: '+c.limit;$('params').value='{}';$('paramHelp').textContent=c.chapter===7?'Optional: {"current_na": 0.2, "dt_ms": 0.5, "duration_ms": 200}':c.chapter===10?'Optional: {"corrected_source": 2}':c.chapter===15?'Optional: {"beta": 1, "gamma": 2, "n": 4000}':'This recipe uses fixed, inspectable parameters; edit the Python engine for deeper experiments.';$('result').hidden=true;$('status').textContent='Ready. The protocol will be hashed before computation.';drawNav();}
function drawNav(){let nav=$('chapters');nav.replaceChildren();let query=$('search').value.toLowerCase();chapters.filter(c=>(c.title+' '+c.lab_title).toLowerCase().includes(query)).forEach(c=>{let b=document.createElement('button');b.textContent=String(c.chapter).padStart(2,'0')+'  '+c.lab_title;if(selected&&selected.id===c.id)b.className='active';b.onclick=()=>choose(c);nav.appendChild(b);});}
function summaries(obj,prefix='',depth=0,out=[]){if(depth>2)return out;for(const [k,v] of Object.entries(obj)){if(out.length>=12)break;if(typeof v==='number'||typeof v==='boolean'){out.push([prefix+k,v]);}else if(v&&typeof v==='object'&&!Array.isArray(v))summaries(v,prefix+k+' / ',depth+1,out);}return out;}
function series(obj,prefix='',out=[]){if(!obj||typeof obj!=='object'||out.length>=5)return out;for(const[k,v]of Object.entries(obj)){if(k==='series'&&Array.isArray(v)&&v.length&&Array.isArray(v[0]))out.push({name:prefix||'signal',points:v});else if(v&&!Array.isArray(v)&&typeof v==='object')series(v,prefix?prefix+' / '+k:k,out);if(out.length>=5)break;}return out;}
function drawChart(traces){$('chartBox').hidden=!traces.length;if(!traces.length)return;let canvas=$('chart'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,pad=45;ctx.clearRect(0,0,W,H);let pts=traces.flatMap(t=>t.points),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(ymin===ymax)ymax=ymin+1;if(xmin===xmax)xmax=xmin+1;let X=x=>pad+(W-2*pad)*(x-xmin)/(xmax-xmin),Y=y=>H-pad-(H-2*pad)*(y-ymin)/(ymax-ymin);ctx.font='11px system-ui';ctx.fillStyle='#4e6475';ctx.strokeStyle='#d5e1e8';for(let i=0;i<=4;i++){let y=ymin+i*(ymax-ymin)/4;ctx.beginPath();ctx.moveTo(pad,Y(y));ctx.lineTo(W-pad,Y(y));ctx.stroke();ctx.fillText(y.toFixed(2),2,Y(y)+4);}ctx.fillText(String(xmin),pad,H-15);ctx.fillText(String(xmax),W-pad,H-15);let colors=['#117d73','#2c5bab','#ae6b30','#844e97','#547849'];traces.forEach((t,i)=>{ctx.strokeStyle=colors[i];ctx.lineWidth=2;ctx.beginPath();t.points.forEach((p,j)=>j?ctx.lineTo(X(p[0]),Y(p[1])):ctx.moveTo(X(p[0]),Y(p[1])));ctx.stroke();});$('legend').textContent=traces.map((t,i)=>`${i+1}. ${t.name}`).join(' | ')+' — Up to five series shown; complete data and units are in JSON.';}
$('run').onclick=async()=>{if(!selected)return;let button=$('run');button.disabled=true;$('status').textContent='Computing locally...';try{let response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,seed:Number($('seed').value),parameters:JSON.parse($('params').value)})});let value=await response.json();if(!response.ok)throw new Error(value.error);last=value;$('result').hidden=false;$('metrics').replaceChildren();for(const[k,v]of summaries(value.result)){let box=document.createElement('div');box.className='metric';let b=document.createElement('b'),label=document.createElement('span');b.textContent=typeof v==='number'?(Number.isInteger(v)?String(v):v.toFixed(5)):String(v);label.textContent=k.replaceAll('_',' ');box.append(b,label);$('metrics').append(box);}$('json').textContent=JSON.stringify(value,null,2);$('hash').textContent='PROTOCOL SHA-256: '+value.protocol_hash+'\nRESULT SHA-256: '+value.result_hash;drawChart(series(value.result));$('status').textContent='Complete. Synthetic result computed by the Python engine; ready for inspection.';}catch(e){$('status').textContent='Experiment rejected: '+e.message;$('result').hidden=true;}finally{button.disabled=false;}};
$('export').onclick=()=>{if(!last)return;let url=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=last.chapter.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('search').oninput=drawNav;
fetch('/api/chapters').then(r=>r.json()).then(data=>{chapters=data;choose(data[9]);}).catch(e=>$('status').textContent='Could not load local chapter API: '+e.message);
